services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
      - ./database/initdb/.env:/docker-entrypoint-initdb.d/.env
    ports:
      - "5432:5432"
    env_file:
      - ./database/initdb/.env

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    command: sh -c "sleep 10 && npm start"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: sh -c "sleep 10 && npm start"
